### ISSUE TITLE
VP document size & projection fields

### ISSUE THREAD

**Issue by samuraitruong** [hashgraph/guardian#1350]
### Problem description

At the moment we return all VC inside VP that cause the VP size very  big and heavily impact performance
Below are screenshot of 3 VP and request response already 10MB

![image](https://user-images.githubusercontent.com/1183138/192910752-7b49bc5c-bd34-423a-85f7-4146b11f0bd6.png)

I known that VC document being use in many place include trustchain API and policy block, but we should consider implement projections field if possible to not return everything from database as there multiple limit

- 16MB per document
- 64MB payload for NAT MQ
- Also there a limit of HCS message that can not exceeded 20 chunk of 1kb  = 20kb. 1 timestamps require 20 bytes, so we can have maximum 1024 MRV in 1 VP (this store as relationship in the message) - If that is true, how we handle case that we have lot of small mrv or even zero value MRV (in case we mint Offset token but solar system not running and all MRV sending as zero by IoT device)

**Comment by anvabr** [comment]
We've been looking into this @samuraitruong, so far we did not find any acceptable solutions to these problems. In general it seems your use-case has been stress testing Guardian scalability, and pushing its various building blocks (mongodb, nats, etc) to their limits. I think it'd be worth to consider a different strategy here - to resolve the ingress side requirements. I.e. to throttle/group/aggregate or pre-process the requests in some way to reduce the throughput requirements.

**Comment by voycey** [comment]
@anvabr - our use case is pretty standard, we are literally just dealing with an industrial system that is producing a real-world amount of data. Pre-processing this goes against the tenets of what Guardian is supposed to solve (e.g. MRVs are taken in directly to the system - in such a way that we can solve the first mile).

Just because we are the **first** to be putting this volume through, does not mean that we will be the only ones putting this (and more) volume through the system, I think this project is a good example of what a real single industrial system looks like, and this is a small project - it is easily possible that a larger implementation of this project would be 10x the data.

I am happy to discuss this as to ways we can work around this but I think ultimately there needs to be a solution defined based on the traceability whereby 1 VP = 1024 MRVs - I think its likely we are going to have to change the relationships to either IPFS or we have to look at chaining multiple HCS messages together to handle larger throughput.

The tradeoff is this:

We can fetch data at a longer increment (e.g. 1 minute) while this is in the test phase (we ultimately might not have control over this in a live solution) - this will reduce the number of MRVs to an acceptable limit - HOWEVER, this will mean that the MRVs have a huge amount of carbon inside them and therefore more wastage if trying to fit within 1 NFT = 1 ton of carbon (maybe 200-500 kg carbon wastage per token due to aggregation limits).

This is the conversation we have been running around the splitting of MRVs. 
I think if we can solve this first of all then all of the items in this ticket become controllable?

**Comment by anvabr** [comment]
We are implementing the chunking functionality to address this problem
