### ISSUE TITLE
Apply proper field validations for all the request payloads and return correct http response status/code

### ISSUE THREAD

**Issue by varsha0592** [hashgraph/guardian#1630]
### Problem description
Current guardian API’s do not have proper field validation on input payload/request. API’s accept invalid input data for all  the create/update  requests. 

### Requirements
Incorporate data validation libraries for the required fields in payload for all endpoints. 

### Definition of done
Response for incorrect request payload should return the correct http response status and code. 
For Eg: 
Status code : 400 Bad Request 
Response Body 
{
"Error": "Token name cannot be empty"
}

### Acceptance criteria
No endpoints should accept invalid data in the request .

**Comment by mattsmithies** [comment]
Recommend following REST best practices for response bodies etc.

https://www.baeldung.com/rest-api-error-handling-best-practices

**Comment by varsha0592** [comment]
@mattsmithies Thank you Matt. We will use the suggested best practice for error validation.

**Comment by AlexIvanHoward** [comment]
Adding to the list of scenarios where invalid data is currently accepted by the API:
1. Submitting a document (to a requestVCdocumentBlock) that does not contain all the required fields of the underlying schema.
2. Submitting a document (to a requestVCdocumentBlock) that contains fields not defined in the underlying schema.
3. Submitting a document (to a requestVCdocumentBlock) that does contains fields not correctly formatted according to the underlying schema (e.g., a document with a numeric field formatted as a string field).
4. Submitting a document (to a requestVCdocumentBlock) without having the correct user role ("permissions") for the block.

**Comment by hnamzian** [comment]
I propose the following solution in order to avoid accepting a corrupt data through requestVCDocumentBlock:

a utility function would be created to get block schema object and data passed by client. The signature of this function would be validate(schema, data). The validator function will create a standard Validator object from the schema and then validates data by the validator object. An error will be thrown in case of invalid data such as passing empty field while it is required, or a bad formatted data, etc.

The function itself will be used in the SET_BLOCK_DATA  and SET_BLOCK_DATA_BY_TAG events before set block data

**Comment by anvabr** [comment]
The RequestVcDocumentBlock already does document validation (by schema), after some research following this ticket we found that there is a timeout issue which cuts off the POST requests at 1 second which is clearly insufficient for sizeable documents. We will fix this as part of the 2.12.1 hotfix.

The error that’s returned by validation (currently) is what the Ajv library returns, which is probably a good practice since this is the library the client app would (should!) likely use to validate the docs prior to submission.

The remaining issue is that no timeout setting can cover all possible document sizes, so the real issue here is that the synchronous mechanism for the response - this mechanism should be changed to asynchronous for those blocks where long-running POST requests are possible.
