### ISSUE TITLE
Create multi-environment configurations using config.js

### ISSUE THREAD

**Issue by hnamazianeu** [hashgraph/guardian#1693]
**Description:**
Config.js is an npm package that helps with managing multi-environment setup that automatically loads configurations associated with the environment set by the NODE_ENV variable. The config files must be stored with the same names as the NODE_ENV variables in .yml, .yaml, .xml, .coffee, .cson, [.properties](https://github.com/gagle/node-properties), [.json](http://json.org/), [.json5](http://json5.org/), [.hjson](http://laktak.github.io/hjson/), .ts or .js format. Consequently all variables must be moved from .env files into json/yaml config files.

**Definition of Done:**
All configurations must be moved from .env files into json/yaml files inside the config directory of each service. The config package must be configured to load configurations from the specified config directory. A template file must also be created in order to be cloned for creating a new config file. Additionally, a new file named custom-environment-variables.json in the config directory must be created in order to add the mapping of environment variables to your configuration. 

**Acceptance Criteria:**
The proper configurations associated with an environment must be selected automatically by just setting the NODE_ENV variable in the global .env file. The configurations must be all stored as json/yaml files instead of .env files per service.

**Comment by voycey** [comment]
Hi Hussain, 
As discussed on the call I feel that environment scoped configurations can cause significant problems.

The majority of hosting now has moved beyond the traditional VM set up (for which I agree your set up makes sense - after all you would have a different VM for each stage and would like to be able to use the same codebase for each VM and then just tell it what set of configurations values to use).

However with the uptake of containerisation, a single set of environment variables that are then "populated" according to what environment they represent is a much cleaner way of doing things.

You can of course still use these configuration files to populate the environment should you wish, but the application should only be implementing the specific values from the environment rather than having any knowledge about what environment it is running on.
