### ISSUE TITLE
Fields for storing user input to Selector Dialog buttons' dialogs.

### ISSUE THREAD

**Issue by AlexIvanHoward** [hashgraph/guardian#1716]
### Problem description
When using the Selector Dialog type for a button in a buttonBlock, the text entered by the user is automatically saved to the relevant document's root.comment field. This is problematic when the document will be reviewed/handled by multiple users who may each want to provide a comment via a Selector Dialog, because every user's comment will then override the comment of the previous user. 

### Requirements
Let the policy developer specify the field to which a Selector Dialog button's user input text must be saved. This field should be one of the fields under root.option (i.e., those accessible as 'Attributes' when using the Guardian Configurator).

### Definition of done
When adding a Selector Dialog button to a policy, the policy developer should be able to specify the field to which the text inputs to the dialog should be saved.

### Acceptance criteria
When adding a Selector Dialog button the a policy, the policy developer should be able to specify the field to which the text inputs to the dialog should be saved.

**Comment by anvabr** [comment]
@AlexIvanHoward reading your requirements do I understand correctly that the use-case you are trying to cover is to enable multiple users to 'record' comments - i.e. to save all the comments? I am asking because the solution that you describe (per my understanding) does not address it, the comments will still be overwritten albeit in the new (custom defined) field.

To address this requirement we can make the comment field an array, and store the comments in there. Or we can make it a Map, which would enable us to specify a key for the comment which I guess would be similar in some way to your description above. As it stands now I am inclined to use the Array option, so would like to check whether that 'key' in the Map is required - if so please explain the use case? Thank you!

**Comment by AlexIvanHoward** [comment]
Hi @anvabr. In our use case we have four different roles to the policy and a single user per role per project. Each of the four roles have one selector-dialog buttonBlock that they must use to review the same document. We want to capture each role (i.e. each user's) review "comments", so they cannot be written to the same field, unless it is a mapped field (as you state). The problem with a mapped field is that, if we were to display the comments on a document to some role in a document grid, they will naturally see the comments of all the other roles too - which is not something that should happen in our use case.  

The MVP is to have the policy developer be able to create an unmapped, custom field to which the answers of a selector-dialog buttonBlock should be written.

The best solution, however, would meet the following requirements simultaneously:
- The field to which a selector-dialog buttonBlock stores its text answers should automatically be a mapped field, but with the option available to the policy developer to make it an unmapped field, should they deliberately want an answer to overwrite the previous one.
- The policy developer should be able to create custom fields to which selector-dialog buttonBlocks store their text answers (one such custom field per selector-dialog buttonBlock).
- When displaying a mapped field in an interfaceDocumentsSourceBlock (i.e., a grid), the policy developer should be able to specify whether all the comments in the mapped field should be displayed to a user, or whether only the comments of specific roles should be displayed.
