### ISSUE TITLE
Unable to configure Guardian services

### ISSUE THREAD

**Issue by anil8797** [hashgraph/guardian#1999]
### Problem description
gurdian/env.docker
MQ_ADDRESS="message-broker"
SERVICE_CHANNEL="guardian.1"
DB_HOST="mongo"
DB_DATABASE="guardian_db"
INITIAL_BALANCE="100"
INITIAL_STANDARD_REGISTRY_BALANCE="100"
OPERATOR_ID="0.0.1449"
OPERATOR_KEY="302e020100300506032b657004220420a590bcd4b3f2bdecfb8d5bf6eb260d3a29503fda0e568ba76691c4ff9a9bb85b"
INITIALIZATION_TOPIC_ID="0.0.2030"
HEDERA_NET="testnet"
MESSAGE_LANG="en-US"
LOG_LEVEL="1"
SEND_KEYS_TO_VAULT="TRUE"
MULTI_POLICY_SCHEDULER="0 0 * * *"
CONTRACT_FILE_ID="0.0.6276"
BBS_SIGNATURES_MODE="WASM"
#HEDERA_CUSTOM_NODES={"0.testnet.hedera.com:50211":"0.0.3"}
#HEDERA_CUSTOM_MIRROR_NODES=["testnet.mirrornode.hedera.com:443"]
#MQ_MESSAGE_CHUNK=5000000
#MAP_API_KEY="..."

and gurdian/env variable as 
MQ_ADDRESS="localhost"
SERVICE_CHANNEL="guardian.1"
DB_HOST="localhost"
DB_DATABASE="guardian_db"
INITIAL_BALANCE="100"
INITIAL_STANDARD_REGISTRY_BALANCE="100"
OPERATOR_ID="0.0.1449"
OPERATOR_KEY="302e020100300506032b657004220420a590bcd4b3f2bdecfb8d5bf6eb260d3a29503fda0e568ba76691c4ff9a9bb85b"
INITIALIZATION_TOPIC_ID="0.0.2030"
HEDERA_NET="testnet"
MESSAGE_LANG="en-US"
LOG_LEVEL="1"
SEND_KEYS_TO_VAULT="TRUE"
MULTI_POLICY_SCHEDULER="0 0 * * *"
CONTRACT_FILE_ID="0.0.6276"
BBS_SIGNATURES_MODE="WASM"
#HEDERA_CUSTOM_NODES={"0.testnet.hedera.com:50211":"0.0.3"}
#HEDERA_CUSTOM_MIRROR_NODES=["testnet.mirrornode.hedera.com:443"]
#MQ_MESSAGE_CHUNK=5000000
#MAP_API_KEY="..."

### Screenshots
![image](https://user-images.githubusercontent.com/121919823/230961217-9b2762fa-fd22-4c2a-83b7-acc2c72397f1.png)

**Comment by prernaadev01** [comment]
@anil8797 Thank you raising the ticket.
We have discussed it internally and would like you to please try below options:
1. Restart all the services
2. Seems like, your Operator ID and Operator Key already exists in DB/Vault, in order to change it , please change your settings in Admin Panel and update ID and Key with the above mentioned one and try to run it once. 

Please let us know if any of the above options works.

Thanks.
