### ISSUE TITLE
Unable to create token retire request .

### ISSUE THREAD

**Issue by varsha0592** [hashgraph/guardian#2000]
### Problem description
Unable to create token retire request .

### Step to reproduce

- Import and publish policy( IREC 4)
- mint token
- create contract and contract pair
- create retire request

### Expected behavior
Token retire request should be created succesfully

### Screenshots
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/118208225/231102842-5c48f912-140e-48dc-97fd-a211b5d43151.png">

**Comment by Neurone** [comment]
[Current retirement contract](https://github.com/hashgraph/guardian/blob/f8eea4ded779ff93444939295731f1a9557a1df8/contracts/RetirementContract.sol) is based on the old smart contract security model. Since v0.35.2, Hedera implemented a [new smart contract security model](https://github.com/hashgraph/hedera-services/releases/tag/v0.35.2) that prevents some capabilities leveraged by the retirement contract when dealing with HTS precompiles.

Waiting for the new architecture (_Contract-based delegation for token retirement operations_ #2011) to be implemented, a potential workaround is to add some transactions to the workflow to set the correct permissions for the smart contract to be able to operate as previously meant.

The exact transactions to be sent depends on the operations the current contract is doing, in particular we can identify the following HTS operations:

- grantTokenKyc
  - a dedicated tx must be sent to update the KYC flag
- associateToken
  - a dedicated tx must be sent to grant association to the token
- transferToken
  - a dedicated tx must be sent to allow the contract to operate on the specific tokens it wants to transfer
- transferNFT
  - a dedicated tx must be sent to allow the contract to operate on the specific tokens it wants to transfer
- wipeTokenAccount
  - I don't have a tested workaround for this behavior yet. I need to verify if wiping is still available without changing the architecture of the contract 
- wipeTokenAccountNFT
  - I don't have a tested workaround for this behavior yet. I need to verify if wiping is still available without changing the architecture of the contract
