### ISSUE TITLE
guardian-ipfs-node-1 container exits during start-up

### ISSUE THREAD

**Issue by AlexIvanHoward** [hashgraph/guardian#2564]
### Problem description
guardian-ipfs-node-1 container exits during start-up.

### Step to reproduce
Follow the Docker approach for setting up a Guardian instance on a Windows 11 machine.

### Expected behavior
The guardian-ipfs-node-1 container should start up successfully.

### Screenshots
![image](https://github.com/hashgraph/guardian/assets/11308324/d813aea4-43d0-4c68-bb92-e94f47e21d4e)

**Comment by Neurone** [comment]
Is this the dev branch? If so, this is possibly due to the recent removal of the IPFS volumes in the docker compose file (https://github.com/hashgraph/guardian/commit/1eb17c849408fbcfb89c92a86f8ba286b3c89aa2#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3). I'm sending a PR to update Kubo to the latest version (`v.0.22.0`), fixing ports configuration and getting the volumes back again.

If it's the main branch, you can try removing the `./runtime-data/ipfs/data` folder or just the `./runtime-data/ipfs/data/repo.lock` file.

**Comment by AlexIvanHoward** [comment]
Thank you for your reply, Guiseppe. It is on the main branch. Dumb question: How does one delete the `./runtime-data/ipfs/data` folder or the `./runtime-data/ipfs/data/repo.lock` file? I'm encountering this on my local Windows machine, so the container contents are in a disk image:
![image](https://github.com/hashgraph/guardian/assets/11308324/8e9b7d42-8dea-40f3-8ece-224abf10f798)

How do I delete stuff from this disk image?

**Comment by AlexIvanHoward** [comment]
I just found the bind mount elsewhere and was able to delete the lock file from there! It now works :) Thank you, Giuseppe!
