### ISSUE TITLE
Incorrect number of NFT are minted when the mint block both mints and transfers

### ISSUE THREAD

**Issue by CyndyMo** [hashgraph/guardian#2833]
**Issue**:

Came across an issue minting on mainnet 10/31. We requested to mint 100 NFT from SMOKETEST token 0.0.3206058. This should have been serials 201-300. However, it minted to serial 310 (201-310). You can see that in total supply on the token and the creation date of the NFT.
I can verify in the trust chain that only 100 NFT were requested. This was the only mainnet mint request we made yesterday.
We investigated and serials 211-220 were minted but not transferred to a custody account, as requested in the mint block. The transaction for these serials is https://explore.lworks.io/mainnet/transactions/0.0.3154258-1698786232-293371358
Thankfully these are smoketest tokens, but it is concerning behavior that NFT are being minted, with Guardian data attached, that were not requested (and approved) in the issue request. We are also paying for this transaction, which may not be a big deal at 5 cents per one time, but if it continues to happen that we generate 10% extra NFT in mainnet the costs will add up quickly.

**Diagnosis**:

Alex Pyatakov:

. We investigated this and it seems like it is not related to your policy. In logs I can see this error
TokenMintNFTTransaction
190e37dc-7904-4f6d-966d-1e0df32b7964
0.0.3154258
max attempts of 10 was reached for request with last error being: GrpcServiceError: gRPC service failed with status: TIMEOUT

Tokens were minted, but then hedera client in the Guardian service wasn't able to establish a connection with Hedera node to transfer these tokens. Mint and transfer currently happens in one operation (I'm oversimplifying here since we have a lot of operations happening simultaneously), so failed transfer led to another attempt to mint and transfer tokens (edited)

**Expected behavior**:

On failure of transfer, only the transfer operation would be retried, or the entire operation would be rolled back and retried. The end result is that the number of NFT minted must be exactly the number that are approved in the mint request.

**Comment by anvabr** [comment]
@CyndyMo thank you for reporting the issue.

The root of the problem here (and in some other cases/bugs) is that in Hedera, unlike in some other ecosystems, transactions are not guaranteed to succeed and there is no automatic failure recovery path - i.e. no guaranteed roll-back of transactions when they don't. Therefore Hedera client applications can end up in situations where out of 5 consecutive actions 1, 3 and 5 succeeded, 2 failed, and 4 really succeeded (e.g. token has been minted) but was reported as failed (e.g. this has been observed to occur in 'timeout' situations). And other various permutations of such. The burden of dealing with these issues seems to be 'outsourced' to Hedera client applications, which makes Hedera itself simpler and faster but at the expense of significantly more complex application logic. The SDK does not seem to contain any logic to address this either.

We believe that the best path for us to address this and similar issues would be:

- to introduce a smart contract[s] and put minting logic in contract as it would somewhat simplify dealing with error conditions 
- to add an additional dedicated 'worker' which would be responsible for error recovery (retries, reporting, etc)

@CyndyMo however the above approach would have effect on the existing tokens already issued because it would require:

- Replacement the current token supply key with ContractId
- Making the contract to be a treasury account of the token

We need to understand the impact on your business before we move forward with this.

**Comment by anvabr** [comment]
@CyndyMo created #2905 as this is a generic fix which would require a dedicated project for design etc work, it's better tracked as an issue we will also manage the bug accordingly.
