### ISSUE TITLE
Don't close dialogues on 'escape' key presses, require explicit <cancel> button press

### ISSUE THREAD

**Issue by anvabr** [hashgraph/guardian#661]
### Problem description
Currently Guardian UI displays pop-up dialogues in various places requiring entries, which can be closed on 'escape' button press. Some of these dialogues contain numerous entry fields, users could spend some time working on them entering values etc. Accidental press of the escape button would then lead to the loss of all this data, and require re-input. Bad UX.

### Requirements
Dialogues should only close on an explicit button press.

### Definition of done
Behaviour change confirmed by QA.

### Acceptance criteria
Each dialogue has a 'cancel' button through which (and only this way) users can close the dialogue.

**Comment by niklatkin** [comment]
Need clarification for this ticket, because it seems like it is still possible to close the dialogue windows with the escape key. As an example create a new policy window.

![Screen Shot 2022-04-06 at 1.41.31 PM.png](https://images.zenhubusercontent.com/6228d071c8dbf81a23fe7447/55ab73a0-e61f-46f9-b6e6-6c0b22a71c15)

**Comment by niklatkin** [comment]
QA PASSED. After cleaning docker and rebuilding the develop branch
