### ISSUE TITLE
Policy Differentiation Feature

### ISSUE THREAD

**Issue by blockchain-biopharma** [hashgraph/guardian#85]
### Problem description
Different Standard Registries (SRs) can be managing policies of varying degree of compatibility, issuing tokens as a result. Policies could be essentially the same and vary in version, or differ in various parts including accounting methods. SRs themselves can be of different degree of 'trustworthiness' and reputation. Participants in the ecological market currently have no way of establishing the relative status of policies issued by different or the same SR at different stages. 

### Requirements
Introduce the functionality to 'diff' policies, where policies can be compared against each other in the following dimensions
- blocks
- transitions between blocks
- roles/actors

As the result of the diff operation the system should produce a numerical score (e.g. saying 'these policies are 68% compatible') as well as the list of all differences.

### Definition of done
Guardian users can determine the difference in policies, via UI and through the API.

### Acceptance criteria

- The comparison is deterministic, i.e. re-running the comparison for the same 2 policies should result in exactly the same score and the list of incompatibilities
- Elements of the policy are considered 'the same' if they are semantically equivalent (e.g. the same json block but with re-ordered entries should be viewed as the same).
- At this stage there is no requirement to produce a verifiable record of the comparison results.

**Comment by envisionblockchainpm** [comment]
We need research done by Max and Andrey. Note: Wes will be the main stakeholder on this.

**Comment by anvabr** [comment]
Reading this description it is not clear what the purpose of this capability/feature request is and therefore what is currently written here can be interpreted in a number of ways. @sergmetelin @dubgeis  we need clarification of the requirements please, specifically to 'why/what' is this required rather than 'how'. Here are some of the questions I have in my mind:

- Is this about the 'backward compatibility' to do with versioning of the same policy (by the same root authority) or the 'equivalence' of two separate policies in the most generic case produced by different root authorities?
- Is the goal of this to be able to 'compare' tokens produced by/under different policies?
- If the above is true, is there scope for a 'market'-driven value comparison (ie 'exchange rate') or is it only yes/no?

**Comment by anvabr** [comment]
See the evolution of this ticket in #1793.
